### ISSUE TITLE
Could not find font file

### ISSUE THREAD

**Issue by Alzarath** [archshift/adusk#1]
```
$ sudo adusk
Found YAML file at `/usr/share/adusk//cfg/keyboard-layout.yaml`
Traceback (most recent call last):
  File "/usr/bin/adusk", line 5, in <module>
    adusk.main()
  File "/usr/lib/python3.5/site-packages/adusk/adusk.py", line 39, in main
    scr = screen.Screen()
  File "/usr/lib/python3.5/site-packages/adusk/screen.py", line 51, in __init__
    assert font_path is not None, "Could not find font file `{}`!".format(font_name)
AssertionError: Could not find font file `fonts/DejaVuSansCondensed-Bold.ttf`!
```

This is happening under Arch Linux x86_64. I can verify that I have the AUR package `ttf-dejavu` installed and that the file /usr/share/fonts/TTF/DejaVuSansCondensed-Bold.ttf exists.

**Comment by archshift** [comment]
Can you confirm that f9d0cf3c20debf90cd6e5018cb28ec6385b80867 fixed this issue?

adusk doesn't yet search for system-installed fonts, and I had forgotten to install the provided DejaVu font with the other data file[s].

**Comment by Alzarath** [comment]
Yes, it now starts without errors. There are some unrelated issues, though.

Running it when Steam is running gives priority to Steam's behavior, making it ignore adusk and use the regular mouse control.

The virtual keyboard doesn't seem to give any input when it's not running as root excluding hitting the 'Done' button. Otherwise, running as root seems to work as intended.

**Comment by archshift** [comment]
Huh, very strange that input isn't working for you except under root. I'm also using Arch...

Would you mind creating new issues for those two? I'm afraid, though, that both these issues might actually be problems with [the driver](https://github.com/ynsta/steamcontroller) rather than the virtual keyboard, but I'd still like to take a look.
