### ISSUE TITLE
No input when not run as root

### ISSUE THREAD

**Issue by Alzarath** [archshift/adusk#3]
While adusk is run as a non-root user the keyboard input does not work. The Done button does, however, close adusk. Running as root works as expected.

**Comment by archshift** [comment]
Some random querying as to your system:
- Are you using the default, latest Linux kernel?
- Which DE/WM are you using?
- Likewise, which library does your system handle its generic HIDs? libinput?

**Comment by Alzarath** [comment]
- I recently performed a full system update, so I imagine so.
- I use [bspwm](https://github.com/baskerville/bspwm).
- Probably whatever the default is. Don't know enough to tinker with it. I do have libinput installed.

**Comment by Xylemon** [comment]
Make sure you have the appropriate udev rule for the Steam Controller: https://aur.archlinux.org/packages/python-steamcontroller-git/ and If you are using eudev, make sure you are put of the input group. This was the case for me.

**Comment by Alzarath** [comment]
I think that was my issue. It's been a while since I added that and tried using adusk, though. Anyways it works as expected.
